/**
 * RubyDocProvider - Thin wrapper over rubydoc.info's YARD-generated gem documentation
 * pages. Verified against live pages (pundit, sidekiq) before writing this: every gem
 * doc page rubydoc.info serves is generated by the same YARD HTML template, so the
 * selectors below (`.method_details`, `.docstring .discussion`, `.tags .param`,
 * `.tags .return`, an `id="{method}-{class|instance}_method"` heading) are standard
 * YARD markup, not something specific to one gem — but it's still undocumented,
 * third-party HTML, so every extraction step degrades to `null`/empty rather than
 * throwing, exactly like ApiDockClient.
 *
 * Gem docs are immutable per version, so this caches far longer (7 days default) than
 * ApiDockClient's community notes. No `vscode` import, so it can run inside the
 * standalone MCP server process (see src/mcp/server.ts's file header) as well as the
 * extension host.
 */

import { LruCache } from '../util/LruCache'
import { stripHtmlTags, decodeHtmlEntities } from '../util/HtmlText'

export interface RubyDocParam {
  name: string
  type: string
  description: string
}

export interface RubyDocEntry {
  gem: string
  version: string
  className: string
  methodName: string
  signature: string | null
  description: string | null
  params: RubyDocParam[]
  returnType: string | null
  sourceLocation: string | null
  url: string
}

export interface RubyDocProviderOptions {
  cacheSize?: number
  cacheTtlMs?: number
  timeoutMs?: number
  baseUrl?: string
}

const DEFAULT_CACHE_SIZE = 200
const DEFAULT_CACHE_TTL_MS = 7 * 24 * 60 * 60 * 1000
const DEFAULT_TIMEOUT_MS = 6000
const DEFAULT_BASE_URL = 'https://www.rubydoc.info'

interface CacheEntry {
  value: RubyDocEntry | null
  expiresAt: number
}

export class RubyDocProvider {
  private cache: LruCache<string, CacheEntry>
  private cacheTtlMs: number
  private timeoutMs: number
  private baseUrl: string

  constructor(options: RubyDocProviderOptions = {}) {
    this.cache = new LruCache(options.cacheSize ?? DEFAULT_CACHE_SIZE)
    this.cacheTtlMs = options.cacheTtlMs ?? DEFAULT_CACHE_TTL_MS
    this.timeoutMs = options.timeoutMs ?? DEFAULT_TIMEOUT_MS
    this.baseUrl = (options.baseUrl ?? DEFAULT_BASE_URL).replace(/\/$/, '')
  }

  async fetchMethod(gem: string, version: string, className: string, methodName: string): Promise<RubyDocEntry | null> {
    const key = `${gem}/${version}/${className}/${methodName}`
    const cached = this.cache.get(key)
    if (cached && cached.expiresAt > Date.now()) {return cached.value}

    const value = await this.request(gem, version, className, methodName)
    this.cache.set(key, { value, expiresAt: Date.now() + this.cacheTtlMs })
    return value
  }

  private async request(gem: string, version: string, className: string, methodName: string): Promise<RubyDocEntry | null> {
    const classPath = className.replace(/::/g, '/')

    const versionedUrl = `${this.baseUrl}/gems/${encodeURIComponent(gem)}/${version}/${classPath}`
    const versionedHtml = await this.fetchText(versionedUrl)
    if (versionedHtml) {
      return parseMethodPage(versionedHtml, gem, version, className, methodName, versionedUrl)
    }

    // Some gems don't publish per-version doc snapshots — fall back to the
    // (still real, just not version-pinned) unversioned page rather than failing outright.
    const unversionedUrl = `${this.baseUrl}/gems/${encodeURIComponent(gem)}/${classPath}`
    const unversionedHtml = await this.fetchText(unversionedUrl)
    if (unversionedHtml) {
      return parseMethodPage(unversionedHtml, gem, version, className, methodName, unversionedUrl)
    }

    return null
  }

  private async fetchText(url: string): Promise<string | null> {
    try {
      const res = await fetch(url, { signal: AbortSignal.timeout(this.timeoutMs) })
      if (!res.ok) {return null}
      return await res.text()
    } catch {
      return null
    }
  }
}

export function parseMethodPage(
  html: string,
  gem: string,
  version: string,
  className: string,
  methodName: string,
  url: string,
): RubyDocEntry | null {
  const headingPattern = new RegExp(
    `<h3[^>]*id=["']${escapeRegExp(methodName)}-(?:class|instance)_method["'][^>]*>([\\s\\S]*?)<\\/h3>`,
  )
  const heading = headingPattern.exec(html)
  if (!heading) {return null}

  const blockStart = html.lastIndexOf('<div class="method_details', heading.index)
  const from = blockStart !== -1 ? blockStart : heading.index
  const nextBlock = html.indexOf('<div class="method_details', heading.index + heading[0].length)
  const block = html.slice(from, nextBlock !== -1 ? nextBlock : html.length)

  return {
    gem,
    version,
    className,
    methodName,
    signature: normalizeText(stripHtml(heading[1])) || null,
    description: extractDocstring(block),
    params: extractParams(block),
    returnType: extractReturnType(block),
    sourceLocation: extractSourceLocation(block),
    url: `${url}#${methodName}-instance_method`,
  }
}

function extractDocstring(block: string): string | null {
  const match = /<div class="docstring">\s*<div class="discussion">([\s\S]*?)<\/div>\s*<\/div>/.exec(block)
  if (!match) {return null}
  const text = normalizeText(stripHtml(match[1]))
  if (!text) {return null}
  return text.length > 600 ? `${text.slice(0, 600).trimEnd()}…` : text
}

function extractParams(block: string): RubyDocParam[] {
  const paramList = /<ul class=["']param["']>([\s\S]*?)<\/ul>/.exec(block)
  if (!paramList) {return []}

  const params: RubyDocParam[] = []
  const liPattern = /<li>([\s\S]*?)<\/li>/g
  let li: RegExpExecArray | null
  while ((li = liPattern.exec(paramList[1])) !== null) {
    const liHtml = li[1]
    const name = /<span class=["']name["']>([\s\S]*?)<\/span>/.exec(liHtml)
    if (!name) {continue}
    const type = /<span class=["']type["']>([\s\S]*?)<\/span>/.exec(liHtml)
    const desc = /<div class=["']inline["']>([\s\S]*?)<\/div>/.exec(liHtml)
    params.push({
      name: normalizeText(stripHtml(name[1])),
      type: type ? normalizeText(stripHtml(type[1])).replace(/^\(|\)$/g, '') : '',
      description: desc ? normalizeText(stripHtml(desc[1])) : '',
    })
  }
  return params
}

function extractReturnType(block: string): string | null {
  const returnList = /<ul class=["']return["']>([\s\S]*?)<\/ul>/.exec(block)
  if (!returnList) {return null}
  const type = /<span class=["']type["']>([\s\S]*?)<\/span>/.exec(returnList[1])
  if (!type) {return null}
  const text = normalizeText(stripHtml(type[1])).replace(/^\(|\)$/g, '')
  return text || null
}

function extractSourceLocation(block: string): string | null {
  const match = /#\s*File\s+['"]([^'"]+)['"],\s*line\s*(\d+)/.exec(block)
  return match ? `${match[1]}:${match[2]}` : null
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
}

const INLINE_FORMATTING_TAGS = /<\/?(?:strong|tt|em|b|i)\b[^>]*>/g

function stripHtml(fragment: string): string {
  // Inline formatting tags (<strong>authorize</strong>(args) in a signature) drop out
  // with no replacement so they don't introduce a spurious space before "(args)";
  // everything else (block-level structure) becomes a space, same as ApiDockClient.
  // Looped to a fixed point (via stripHtmlTags, not a single .replace()) same as the
  // second pass below — a single non-recursive pass over a narrow tag set is exactly
  // the "incomplete sanitization" gap CodeQL flags, regardless of which tags it targets.
  const withoutInlineTags = stripHtmlTags(fragment, '', INLINE_FORMATTING_TAGS)
  return decodeHtmlEntities(stripHtmlTags(withoutInlineTags))
}

function normalizeText(text: string): string {
  return text.replace(/\s+/g, ' ').trim()
}
