source 'https://rubygems.org'
ruby '3.3.0'

gem 'rails', '~> 7.1.0'
gem 'sqlite3', '~> 1.7'
gem 'puma', '~> 6.4'
gem 'turbo-rails', '~> 2.0'
gem 'stimulus-rails', '~> 1.3'
gem 'pundit', '~> 2.3'
gem 'view_component', '~> 3.10'
gem 'strong_migrations', '~> 1.8'
gem 'jbuilder', '~> 2.11'

group :development, :test do
  gem 'rspec-rails', '~> 6.1'
  gem 'brakeman', '~> 6.0'
  gem 'rubocop', '~> 1.60'
  gem 'pry', '~> 0.14'
end
