require "bundler/gem_tasks"
require "rspec/core/rake_task"

RSpec::Core::RakeTask.new(:spec)

task default: :spec

namespace :build do
  desc "Compile native C extensions if any"
  task :native do
    puts "Checking native extensions..."
  end
end
