/**
 * CursorRulesGenerator - Phase 14: writes .cursor/rules/railsforge.mdc so Cursor's
 * (or any `.mdc`-reading) agent gets the same grounding RailsAgent's system prompt
 * already builds for the local @rails chat participant — schema, routes, existing
 * patterns, and the "search before generating" rule — without requiring that agent
 * to go through Ollama or the VS Code extension host at all.
 */

import { SchemaTable } from '../rails/SchemaIndexer'
import { RailsRoute } from '../rails/RoutesIndexer'
import { IndexedPattern, PatternType } from '../patterns/ProjectPatternIndexer'
import { ProjectType } from '../environment/EnvironmentDetector'

export interface CursorRulesInput {
  rubyVersion: string
  railsVersion?: string
  hasRails: boolean
  projectType?: ProjectType
  tables: SchemaTable[]
  routes: RailsRoute[]
  patterns: IndexedPattern[]
  mcpServerAvailable: boolean
}

export function buildCursorRulesContent(input: CursorRulesInput): string {
  const parts: string[] = [
    '---',
    'description: RailsForge project grounding (auto-generated — re-run "RailsForge: Export Cursor Rules" after schema/routes/pattern changes)',
    'alwaysApply: true',
    '---',
    '',
    '# Project Context (generated by RailsForge)',
    '',
    input.hasRails
      ? `This is a Rails ${input.railsVersion ?? 'unknown'} project on Ruby ${input.rubyVersion}. Do not use or suggest APIs from newer Ruby/Rails versions.`
      : `This is a standalone Ruby project (not Rails) on Ruby ${input.rubyVersion}. Do not assume ActiveRecord/ActionController or other Rails framework APIs are available.`,
    ...projectTypeNote(input.projectType),
    '',
    '## Rules',
    '',
    '- Before generating a new Service, Query, Form, Policy, or Decorator, check the "Existing Patterns" list below for a close match and reuse/extend it instead of writing a new one from scratch.',
    '- Follow SOLID principles; avoid fat controllers/models; extract business logic to Service Objects.',
    '- Prevent N+1 queries: use `.includes`/`.eager_load` for association access in loops.',
  ]

  if (input.mcpServerAvailable) {
    parts.push(
      '- The `railsforge` MCP server is available with tools `get_schema`, `list_routes`, `list_patterns`, `find_similar_pattern`, `get_dependencies`, and `find_duplicate_methods` — prefer calling these for up-to-date project context over relying solely on this file.',
    )
  }

  if (input.tables.length > 0) {
    parts.push('', '## Database Schema', '')
    for (const table of input.tables) {
      const columns = Array.from(table.columns.values()).map(c => `${c.name}:${c.type}`).join(', ')
      parts.push(`- \`${table.name}\`: ${columns}`)
    }
  }

  if (input.routes.length > 0) {
    parts.push('', '## Routes (first 40)', '')
    for (const route of input.routes.slice(0, 40)) {
      parts.push(`- ${route.verb} \`${route.uriPattern}\` → \`${route.controller}#${route.action}\``)
    }
  }

  if (input.patterns.length > 0) {
    parts.push('', '## Existing Patterns', '')
    const byType = groupByType(input.patterns)
    for (const [type, patterns] of byType) {
      parts.push(`- **${type}**: ${patterns.map(p => p.name).join(', ')}`)
    }
  }

  return `${parts.join('\n')}\n`
}

function projectTypeNote(projectType: ProjectType | undefined): string[] {
  switch (projectType) {
    case 'api_only':
      return ['This is an API-only Rails app — do not suggest ERB/HAML/Slim views, view helpers, or the asset pipeline; responses are JSON (or similar) rendered directly from controllers/serializers.']
    case 'gem':
      return ['This is a Ruby gem, not a Rails application — do not assume ActiveRecord/ActionController or any Rails framework APIs are available unless the gem explicitly declares a Rails dependency.']
    default:
      return []
  }
}

function groupByType(patterns: IndexedPattern[]): Array<[PatternType, IndexedPattern[]]> {
  const map = new Map<PatternType, IndexedPattern[]>()
  for (const pattern of patterns) {
    const list = map.get(pattern.type) ?? []
    list.push(pattern)
    map.set(pattern.type, list)
  }
  return Array.from(map.entries())
}
