source 'https://rubygems.org'
ruby '3.3.0'

gem 'rails', '~> 7.1.0'
gem 'sqlite3', '~> 1.7'
gem 'puma', '~> 6.4'

group :development, :test do
  gem 'rspec-rails', '~> 6.1'
  gem 'rubocop', '~> 1.60'
  gem 'brakeman', '~> 6.0'
end
